"""criacao da tabela tb_endereco

Revision ID: 57ee94eb8f00
Revises: 
Create Date: 2026-09-09 10:51:43.107887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57ee94eb8f00'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_notas')
    op.drop_table('tb_disciplinas')
    op.drop_table('tb_alunos')
    op.drop_column('tb_enderecos', 'regiao')
    op.drop_column('tb_enderecos', 'bairro')
    op.drop_column('tb_enderecos', 'cidade')
    op.drop_column('tb_enderecos', 'estado')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_enderecos', sa.Column('estado', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('tb_enderecos', sa.Column('cidade', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('tb_enderecos', sa.Column('bairro', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('tb_enderecos', sa.Column('regiao', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_table('tb_alunos',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('matricula', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('nome_aluno', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('endereco_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['endereco_id'], ['tb_enderecos.id'], name=op.f('fk_alunos_endereco'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('tb_alunos_pkey')),
    sa.UniqueConstraint('matricula', name=op.f('tb_alunos_matricula_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('tb_disciplinas',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('nome_disciplina', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('carga', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('semestre', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('tb_disciplinas_pkey'))
    )
    op.create_table('tb_notas',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('aluno_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('disciplina_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nota', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['tb_alunos.id'], name=op.f('fk_notas_aluno'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['disciplina_id'], ['tb_disciplinas.id'], name=op.f('fk_notas_disciplina'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('tb_notas_pkey'))
    )
    # ### end Alembic commands ###
