"""Cria tabelas tb_alunos, tb_disciplinas e tb_notas

Revision ID: 803050a8f23d
Revises: 96a13ec6c1f0
Create Date: 2026-09-16 09:01:41.137082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '803050a8f23d'
down_revision: Union[str, Sequence[str], None] = '96a13ec6c1f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_disciplinas',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('nome_disciplina', sa.String(length=255), nullable=True),
    sa.Column('carga', sa.String(length=255), nullable=True),
    sa.Column('semestre', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_alunos',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('matricula', sa.String(length=20), nullable=True),
    sa.Column('nome_aluno', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('endereco_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['endereco_id'], ['tb_enderecos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_notas',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('nome_id', sa.Integer(), nullable=True),
    sa.Column('disciplina_id', sa.Integer(), nullable=True),
    sa.Column('nota', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['disciplina_id'], ['tb_disciplinas.id'], ),
    sa.ForeignKeyConstraint(['nome_id'], ['tb_alunos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_notas')
    op.drop_table('tb_alunos')
    op.drop_table('tb_disciplinas')
    # ### end Alembic commands ###
