"""Alteracao tb_endereco

Revision ID: 96a13ec6c1f0
Revises: 57ee94eb8f00
Create Date: 2026-09-16 08:49:37.586569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96a13ec6c1f0'
down_revision: Union[str, Sequence[str], None] = '57ee94eb8f00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_enderecos', sa.Column('bairro', sa.String(length=255), nullable=True))
    op.add_column('tb_enderecos', sa.Column('cidade', sa.String(length=255), nullable=True))
    op.add_column('tb_enderecos', sa.Column('estado', sa.String(length=2), nullable=True))
    op.add_column('tb_enderecos', sa.Column('regiao', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_enderecos', 'regiao')
    op.drop_column('tb_enderecos', 'estado')
    op.drop_column('tb_enderecos', 'cidade')
    op.drop_column('tb_enderecos', 'bairro')
    # ### end Alembic commands ###
