"""cria tabelas

Revision ID: 96f579b74376
Revises: 
Create Date: 2026-09-21 20:36:33.585095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96f579b74376'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_disciplinas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_disciplina', sa.String(length=255), nullable=False),
    sa.Column('carga', sa.String(length=255), nullable=False),
    sa.Column('semestre', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_enderecos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cep', sa.String(length=10), nullable=False),
    sa.Column('endereco', sa.String(length=255), nullable=False),
    sa.Column('bairro', sa.String(length=255), nullable=False),
    sa.Column('cidade', sa.String(length=255), nullable=False),
    sa.Column('estado', sa.String(length=2), nullable=False),
    sa.Column('regiao', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cep')
    )
    op.create_table('tb_alunos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matricula', sa.String(length=20), nullable=False),
    sa.Column('nome_aluno', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('endereco_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['endereco_id'], ['tb_enderecos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_notas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_id', sa.Integer(), nullable=False),
    sa.Column('disciplina_id', sa.Integer(), nullable=False),
    sa.Column('nota', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['disciplina_id'], ['tb_disciplinas.id'], ),
    sa.ForeignKeyConstraint(['nome_id'], ['tb_alunos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_notas')
    op.drop_table('tb_alunos')
    op.drop_table('tb_enderecos')
    op.drop_table('tb_disciplinas')
    # ### end Alembic commands ###
