"""cria tabelas

Revision ID: ad7654dfb00a
Revises: 803050a8f23d
Create Date: 2026-09-20 18:08:52.164281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad7654dfb00a'
down_revision: Union[str, Sequence[str], None] = '803050a8f23d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tb_alunos', 'matricula',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('tb_alunos', 'nome_aluno',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('tb_alunos', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('tb_alunos', 'endereco_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tb_disciplinas', 'nome_disciplina',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('tb_disciplinas', 'carga',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('tb_disciplinas', 'semestre',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('tb_enderecos', 'bairro',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('tb_enderecos', 'cidade',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('tb_enderecos', 'estado',
               existing_type=sa.VARCHAR(length=2),
               nullable=False)
    op.alter_column('tb_enderecos', 'regiao',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('tb_notas', 'nome_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tb_notas', 'disciplina_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tb_notas', 'nota',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tb_notas', 'nota',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('tb_notas', 'disciplina_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tb_notas', 'nome_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tb_enderecos', 'regiao',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('tb_enderecos', 'estado',
               existing_type=sa.VARCHAR(length=2),
               nullable=True)
    op.alter_column('tb_enderecos', 'cidade',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('tb_enderecos', 'bairro',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('tb_disciplinas', 'semestre',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('tb_disciplinas', 'carga',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('tb_disciplinas', 'nome_disciplina',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('tb_alunos', 'endereco_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tb_alunos', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('tb_alunos', 'nome_aluno',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('tb_alunos', 'matricula',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###
